config_dir = "/Users/ryanbajollari/ojo/pricefeeder/ojo-provider-config"

gas_adjustment = 1
provider_timeout = "1000000s"

[server]
listen_addr = "0.0.0.0:7171"
read_timeout = "20s"
verbose_cors = true
write_timeout = "20s"

[account]
address = "ojo1zypqa76je7pxsdwkfah6mu9a583sju6xzthge3"
chain_id = "ojo-testnet"
validator = "ojovaloper1zypqa76je7pxsdwkfah6mu9a583sju6x6tnq6w"

[keyring]
backend = "test"
dir = "/Users/username/.ojo"

[rpc]
grpc_endpoint = "localhost:9090"
rpc_timeout = "100ms"
tmrpc_endpoint = "http://localhost:26657"

[telemetry]
enable-hostname = true
enable-hostname-label = true
enable-service-label = true
enabled = true
global-labels = [["chain_id", "ojo-devnet-01"]]
service-name = "price-feeder"
prometheus-retention-time = 100
